language: rust
cache: cargo
rust:
  - stable
before_script: rustup component add rustfmt clippy
script:
  - cargo test --all
  - cargo fmt --all -- --check


# auto deploy on crates.io on PR merge (if new version number)
deploy:
  provider: cargo
  on:
    repo: CanalTP/address-formatter-rs
    branch: master
  token:
    secure: "Q3VSXO/sCzv2+hNTuJTJ+nqqu0Fxq/AY5nJ867MY91mX2ztj/mAFtI2mqhAkRl4mnzebenxbNR9m9vSPIqU/oB+x/hDvW0uUnRTGKCOENk0dtgaXMHY1lQqBKq4w6NS5R/tCC5j5Sfb/KekDEY3K8s+QW9Xvb6hIWNOurqOeIsuzhuyNl9akXiLjEFblvPim+DLo3pypdGVUzKYn4RLKVDFkxvDnFPiJ9oCdKX5tOjxJfAnk6rcUcbi13QmlAsAhgQG6UxfXJVC2rKndLaBX1QxEMENj9RZJG3Y9jacNdNYfq3dBo9gL5cgHkZGCIAgWULekcbijowhs6njdez7BCLVRAZj4J2Kf1G6zi8ltnhe8ylci3F5eoPSd98soujtXr2hyp+ZIh3bgZ00uaQ24xzjFXR/KTyqN7HoWRkILAeQUCjXMB/z7+lcqhHhBshvTd4ak1IVU8mgjjOM1ymSIOjIDPY55sHwhd4BlGDnEXW6TIDjlLQhwwRCU9U8y/Eq5pzBIx1JKzEoGu4fOH2H24wwJviGbBCs3VrB/+R4BG3EWv7PA2W19ErgV3oZxNNwVmdOUCHxRimisdxj7oZC0EgqUZ/ZJGqjuruI/JvYZefWyMr5iSf1vAo8suwSjusNTGa3HBldqEKp6tkU/VghFG4RPni0K5m2agui5Ho0Sse8="
